AWS_ACCESS_KEY =
AWS_SECRET_KEY =
albname =
privatesubnet =
region =
securitygroupname =
vpccidr =
vpcname =
instance_type = 
nodemonitoringenabled =
mastercount = 3
workercount =
traefikhttpport = 32080
traefikhttpsport = 32443
talostg = 
traefik_tg_80_name = 
traefik_tg_443_name = 
traefiklbname = 
spot_price =
