AWS_ACCESS_KEY =
AWS_SECRET_KEY =
albname =
privatesubnet =
region =
securitygroupname =
vpccidr =
vpcname =
instance_type = 
nodemonitoringenabled =
mastercount = 
workercount =
traefikhttpport = 32080
traefikhttpsport = 32443
nats_client_port = 31675
talostg = 
traefik_tg_80_name = 
traefik_tg_443_name = 
nats_tg_4222_name = 
traefiklbname = 
configfolderpath = 
talosctlfolderpath = 
